on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3 
      
      - name: "Login to dockerhub"
        run: docker login --username ${{secrets.OS_NAME}} --password ${{secrets.OS_PASSWORD}}

      - name: "Build image to docker"
        run: docker build -t ${{secrets.OS_NAME}}/frist-img .  

      - name: "Push image to docker"
        run: docker push  ${{secrets.OS_NAME}}/frist-img     
